package com.example.starborn.domain.session

data class GameSessionState(
    val worldId: String? = null,
    val hubId: String? = null,
    val roomId: String? = null,
    val playerId: String? = null,
    val playerLevel: Int = 1,
    val playerXp: Int = 0,
    val playerAp: Int = 0,
    val playerCredits: Int = 0,
    val partyMemberXp: Map<String, Int> = emptyMap(),
    val partyMemberLevels: Map<String, Int> = emptyMap(),
    val partyMemberHp: Map<String, Int> = emptyMap(),
    val partyMemberRp: Map<String, Int> = emptyMap(),
    val trackedQuestId: String? = null,
    val activeQuests: Set<String> = emptySet(),
    val completedQuests: Set<String> = emptySet(),
    val failedQuests: Set<String> = emptySet(),
    val completedMilestones: Set<String> = emptySet(),
    val milestoneHistory: List<String> = emptyList(),
    val learnedSchematics: Set<String> = emptySet(),
    val unlockedSkills: Set<String> = emptySet(),
    val partyMembers: List<String> = emptyList(),
    val inventory: Map<String, Int> = emptyMap(),
    val equippedItems: Map<String, String> = emptyMap(),
    val tutorialSeen: Set<String> = emptySet(),
    val tutorialCompleted: Set<String> = emptySet(),
    val tutorialRoomsSeen: Set<String> = emptySet(),
    val resonance: Int = 0,
    val resonanceMin: Int = 0,
    val resonanceMax: Int = 100,
    val resonanceStartBase: Int = 0
)
