package com.example.starborn.debug

import com.example.starborn.feature.mainmenu.DebugScenario
import com.example.starborn.feature.mainmenu.DebugScenarioCategory
import com.example.starborn.feature.mainmenu.DebugScenarioDestination

data class CampaignScenarioSpec(
    val id: String,
    val questId: String,
    val title: String,
    val world: String,
    val category: DebugScenarioCategory,
    val roomId: String,
    val procedure: DebugTestProcedure
)

object DebugCampaignScenarios {
    val scenarios: List<DebugScenario> = listOf(
        // World 1 Main Quests (w1_mq01 is in DebugTestRegistry.scenarios)
        entry("campaign_w1_mq02", "w1_mq02", "MQ02: Shift Clearance", "World 1: The Mines", DebugScenarioCategory.STORY, "workshop_yard",
            "Workshop Yard after completing Wake Up Call; Nova has starter gear and cutter bypass confirmed.",
            listOf("Leave Jed's Workshop Yard and navigate to the Checkpoint Queue.",
                "Speak with Guard Hank at the security booth, then speak with Zeke.",
                "Complete the file override dialogue with Zeke to obtain the Mine Access Badge.",
                "Verify Shift Clearance completes and The Echo starts."),
            listOf("Transit Checkpoint routes open legally without debug bypasses.",
                "Zeke dialogue correctly awards the badge and completes the quest.",
                "Shift Clearance completes once and updates the journal."),
            setOf("quests:w1_mq02", "dialogue:hank_w1_mq02_denial_1", "dialogue:zeke_w1_mq02_override_1")),

        entry("campaign_w1_mq03", "w1_mq03", "MQ03: The Echo", "World 1: The Mines", DebugScenarioCategory.STORY, "admin_lobby",
            "Admin Lobby with Shift Clearance completed and the Mine Access Badge equipped; Nova alone.",
            listOf("Confront Foreman Boggs in Admin Lobby and complete the deep mine briefing.",
                "Descend the deep elevator to Mine Landing and defeat the initial encounter.",
                "Reach Cavern Junction, restore auxiliary junction power, and navigate to Echo Gap.",
                "Inspect and touch the ancient Relic in Echo Gap to trigger the sync sequence."),
            listOf("Elevator and deep mine routes unlock upon briefing completion.",
                "Junction power event activates the lower mine lights and routes.",
                "Relic interaction completes The Echo and activates Red Alert."),
            setOf("quests:w1_mq03", "events:evt_mine_power_on", "enemies:echo_borer")),

        entry("campaign_w1_mq04", "w1_mq04", "MQ04: Red Alert", "World 1: The Mines", DebugScenarioCategory.STORY, "echo_gap",
            "Echo Gap immediately after claiming the Relic with lockdown alarms active; Nova alone.",
            listOf("Escape the deep mine lockdown gauntlet back to the Launch Lift.",
                "Engage security forces blocking the lift passage.",
                "Reach the lift to rendezvous with Jed and Zeke.",
                "Witness Jed's sacrifice and receive the Ghost Signal Chime."),
            listOf("Lockdown routes and obstacles require navigating active security hazards.",
                "Jed dialogue cleanly awards the Chime and triggers lift departure.",
                "Red Alert completes once and transitions to The Launch."),
            setOf("quests:w1_mq04", "dialogue:jed_w1_mq04_sacrifice_1")),

        entry("campaign_w1_mq05", "w1_mq05", "MQ05: The Launch", "World 1: The Mines", DebugScenarioCategory.STORY, "launch_lift",
            "Launch Lift platform arriving at Pod Bay with Zeke; ready to confront the Iron Warden.",
            listOf("Enter Launch Bay and confront the Iron Warden boss.",
                "Defeat the Iron Warden using guard break and shock abilities.",
                "Interact with Zeke at the escape pod console and insert the Chime.",
                "Initiate the emergency launch sequence to depart World 1."),
            listOf("The Iron Warden combat initiates cleanly with authored telegraphs and rewards.",
                "Launch pod console requires the Chime to authenticate liftoff.",
                "Pod launch successfully transitions to World 2: Sector 9 crash site."),
            setOf("quests:w1_mq05", "enemies:the_iron_warden", "dialogue:warden_boss_intro_1")),

        // World 1 Side Quests
        entry("campaign_w1_sq01", "w1_sq01", "SQ01: The Scavenger's Stash", "World 1: The Mines", DebugScenarioCategory.CONTENT, "trade_strip",
            "Trade Strip in Homestead with Scrapper's lead active; Nova alone.",
            listOf("Head east from Market Strip in Trade Row to The Hidden Stash.",
                "Pry open the corroded seal on the rebel cache and collect the proof.",
                "Return to Scrapper's Stall in Market Strip to deliver the proof.",
                "Collect rewards and verify journal updates to complete."),
            listOf("Stash location opens and cache container can be looted exactly once.",
                "Scrapper acknowledges the proof and awards the pulse grenades.",
                "Quest completes without blocking future trade interactions."),
            setOf("quests:w1_sq01", "items:pulse_grenade")),

        entry("campaign_w1_sq02", "w1_sq02", "SQ02: System Flush", "World 1: The Mines", DebugScenarioCategory.CONTENT, "medbay_exam1",
            "Doc's Exam Room in Homestead with the ventilation failure active; Nova alone.",
            listOf("Travel east through Triage Hall to the Ventilation Hub.",
                "Inspect the cracked vent housing leaking sulfuric fumes.",
                "Reroute the airflow fans and clear the toxic blockage.",
                "Return to Doc in the Exam Room to report the air quality fix."),
            listOf("Ventilation room hazard clears upon rerouting airflow.",
                "Intake blockage interaction resolves cleanly.",
                "Doc awards Corrosive Rounds mod and quest completes."),
            setOf("quests:w1_sq02", "items:mod_corrosive_rounds")),

        entry("campaign_w1_sq03", "w1_sq03", "SQ03: Heavy Lifting", "World 1: The Mines", DebugScenarioCategory.CONTENT, "admin_lobby",
            "Admin Lobby before Foreman Boggs; ready for mandatory logistics certification.",
            listOf("Speak with Foreman Boggs in the Concourse Lobby.",
                "Operate the cargo loader and rail at Jed's Workshop loading dock.",
                "Enter the Security Post and engage the Shielded Trainer.",
                "Execute Guard Break to break the shield and complete the drill."),
            listOf("Cargo moving actions clear the training arena obstruction.",
                "Shielded Trainer encounter enforces guard-break mechanics.",
                "Certification logs complete and awards heavy gear."),
            setOf("quests:w1_sq03", "enemies:acoustic_bulwark")),

        entry("campaign_w1_sq04", "w1_sq04", "SQ04: Protocol Override", "World 1: The Mines", DebugScenarioCategory.CONTENT, "server_hub",
            "Server Room Core Hub with the scrubbed rebel terminal located; Nova alone.",
            listOf("Enter the Server Room from Air-Lock Entrance through Aisle 01.",
                "Inspect the frozen rebel terminal at The Core Hub.",
                "Thaw the console controls and re-engage the interface.",
                "Apply the rebel access override to extract the security protocol."),
            listOf("Terminal thaw interaction unlocks the access override action.",
                "Rebel override applies cleanly and rewards circuit board.",
                "Quest completes and records rebel milestone."),
            setOf("quests:w1_sq04", "items:circuit_board")),

        entry("campaign_w1_sq05", "w1_sq05", "SQ05: The Lost Shift", "World 1: The Mines", DebugScenarioCategory.CONTENT, "mine_junction",
            "Cavern Junction with auxiliary power restored; ready to investigate collapsed side shunts.",
            listOf("Travel south to Main Tunnel Alpha and enter Side Shunt 4.",
                "Navigate the collapsed tunnel to locate the abandoned miner remains.",
                "Recover the crew datapad from the rubble.",
                "Read the miner's final recorded letter to resolve the lost shift."),
            listOf("Side Shunt 4 is accessible with junction power active.",
                "Datapad inspection displays the final letter log.",
                "Quest completes and awards recoil dampener."),
            setOf("quests:w1_sq05", "items:recoil_dampener")),

        // World 2 Main Quests
        entry("campaign_w2_mq01", "w2_mq01", "MQ01: A Strange Coast", "World 2: Sector 9", DebugScenarioCategory.STORY, "sector9_crash_site",
            "Sector 9 Crash Site with the escape pod wreckage; Zeke injured on the ground.",
            listOf("Talk to Zeke at the wrecked escape pod.",
                "Examine the shattered navigation console to salvage the Chime.",
                "Use the emergency medkit to stabilize Zeke's injuries.",
                "Follow the glow-water stream into the Sector 9 ruins to secure shelter."),
            listOf("Pod inspection recovers the Chime and survival supplies.",
                "Stabilizing Zeke updates his state and allows party traversal.",
                "Reaching Landing Stream completes A Strange Coast."),
            setOf("quests:w2_mq01", "characters:zeke")),

        entry("campaign_w2_mq02", "w2_mq02", "MQ02: The Signal", "World 2: Sector 9", DebugScenarioCategory.STORY, "sector9_landing_stream",
            "Landing Stream in Sector 9 with Zeke in party; tracking the clean distress frequency.",
            listOf("Traverse the overgrown canopy path toward the sanctuary ruins.",
                "Defeat hostile wildlife encounters along Razor Vine Path.",
                "Locate the massive Temple Gate blocking the inner sanctuary.",
                "Slot the recovered Chime into the Temple Gate's resonator to unseal the doors."),
            listOf("Hostile canopy encounters test early party switching and status effects.",
                "Temple Gate resonator interaction validates Chime ownership.",
                "Gate unseals permanently and completes The Signal."),
            setOf("quests:w2_mq02", "items:ghost_signal_cell")),

        entry("campaign_w2_mq03", "w2_mq03", "MQ03: Sleeping Giant", "World 2: Sector 9", DebugScenarioCategory.STORY, "sector9_hall_of_echoes",
            "Hall of Echoes inside Sanctuary with Zeke in party; investigating stasis pods.",
            listOf("Examine the shifting light murals in the Hall of Echoes.",
                "Navigate south into Orion's Stasis Chamber.",
                "Stabilize the emergency coolant lines and bypass the stasis lock.",
                "Complete the chord alignment to wake Orion and recruit him to the party."),
            listOf("Mural inspection unlocks the path to the stasis chamber.",
                "Coolant alignment puzzle resolves cleanly.",
                "Orion awakens, joins the active party, and unlocks Prism Lance."),
            setOf("quests:w2_mq03", "characters:orion", "skills:orion_prism_lance")),

        entry("campaign_w2_mq04", "w2_mq04", "MQ04: The Hunter", "World 2: Sector 9", DebugScenarioCategory.STORY, "sector9_canopy_ridge",
            "Canopy Ridge with Nova, Zeke, and Orion; tracking the apex predator stalker.",
            listOf("Advance along Canopy Ridge to corner the Source Beast.",
                "Confront the stalker and engage in boss combat.",
                "Defeat The Beast exploiting Orion's prism and Nova's shock abilities.",
                "Complete the anchor drill to free Gh0st from the beast's containment."),
            listOf("The Beast encounter features aggressive telegraphs and multi-target attacks.",
                "Victory allows executing the anchor drill.",
                "Gh0st is rescued, joins the party, and completes The Hunter."),
            setOf("quests:w2_mq04", "enemies:the_beast", "characters:gh0st")),

        entry("campaign_w2_mq05", "w2_mq05", "MQ05: Liftoff", "World 2: Sector 9", DebugScenarioCategory.STORY, "sector9_source_gate",
            "Sector 9 Source Gate with the full crew (Nova, Zeke, Orion, Gh0st); preparing the Astra.",
            listOf("Bypass the acoustic lock at the Source Gate using harmonic tuning.",
                "Enter Hangar Bay and inspect the grounded Astra starship.",
                "Collect power conduits and restore primary ship systems.",
                "Reboot the bridge relic and initiate atmospheric launch to the Spire."),
            listOf("Acoustic lock puzzle validates chord combinations.",
                "Hangar repair sequence restores the Astra as the player's mobile base.",
                "Liftoff launches the crew into orbit and arrives at World 3: The Spire."),
            setOf("quests:w2_mq05", "worlds:world_astra")),

        // World 2 Side Quests
        entry("campaign_w2_sq01", "w2_sq01", "SQ01: Botanist", "World 2: Sector 9", DebugScenarioCategory.CONTENT, "sector9_canopy",
            "Resonant Canopy with Zeke; scanning exotic mutated flora.",
            listOf("Locate and scan giant crystalline ferns across the canopy walk.",
                "Scan luminous spore caps in the jungle understory.",
                "Scan bioluminescent moss in the stream pools.",
                "Compile the botanical survey data with Zeke."),
            listOf("Each plant specimen can be scanned once with distinct lore text.",
                "Botanical survey updates progress counter correctly.",
                "Quest completes with herbal ingredients and XP payout."),
            setOf("quests:w2_sq01")),

        entry("campaign_w2_sq02", "w2_sq02", "SQ02: Lost Patrol", "World 2: Sector 9", DebugScenarioCategory.CONTENT, "sector9_wilds_thickets",
            "Spore Thickets with Zeke; tracking distress beacons from a lost Dominion patrol.",
            listOf("Trace distress beacon Alpha through the dense spore thickets.",
                "Locate distress beacon Beta near the cliff overhang.",
                "Recover the patrol commander's beacon and encrypted tags at Gamma.",
                "Decrypt the final transmission log to complete the record."),
            listOf("Beacons activate in sequence following radio triangulation hints.",
                "Encrypted tags require interaction to read the log.",
                "Quest completes and awards weapon mod components."),
            setOf("quests:w2_sq02")),

        entry("campaign_w2_sq03", "w2_sq03", "SQ03: Tideglass Day", "World 2: Sector 9", DebugScenarioCategory.CONTENT, "sector9_beach_pools",
            "Tideglass Beach tide pools with Orion; scavenging coastal resources.",
            listOf("Explore the Tideglass Beach dunes and pillar formations.",
                "Scavenge edible tide fruits and coastal protein from the tide pools.",
                "Synthesize Source Resin at the beach campfire using collected ingredients.",
                "Deliver the resin batch to Orion."),
            listOf("Beach discovery updates node and map state.",
                "Tide pool foraging adds cooking ingredients to inventory.",
                "Crafting Source Resin completes the quest."),
            setOf("quests:w2_sq03")),

        entry("campaign_w2_sq04", "w2_sq04", "SQ04: Ancient Echoes", "World 2: Sector 9", DebugScenarioCategory.CONTENT, "sector9_hall_of_echoes",
            "Hall of Echoes in Sanctuary with Orion; gathering resonance crystals.",
            listOf("Retrieve the western wing resonance crystal from Archive Vault.",
                "Retrieve the eastern wing resonance crystal from Conduit Junction.",
                "Retrieve the northern crystal from the Facility Grand Foyer.",
                "Calibrate the light murals in the Hall of Echoes using the three crystals."),
            listOf("Wing crystals require navigating individual puzzle chambers.",
                "Mural calibration verifies all three crystals are held.",
                "Sanctuary resonance matrix stabilizes and completes quest."),
            setOf("quests:w2_sq04")),

        entry("campaign_w2_sq05", "w2_sq05", "SQ05: Stolen Tech", "World 2: Sector 9", DebugScenarioCategory.CONTENT, "sector9_vents_gantry",
            "Facility High Gantry with Gh0st; recovering classified prototype modules.",
            listOf("Navigate the vent gantry above the facility security grid.",
                "Time the sweep pulses to blind the automated security lasers.",
                "Breach the secure tech alcove and recover the prototype cloaking coil.",
                "Deliver the recovered module to Gh0st."),
            listOf("Vent laser timing requires waiting for safe passage windows.",
                "Tech alcove container requires Gh0st in party to decrypt.",
                "Quest completes and upgrades Gh0st's stealth capabilities."),
            setOf("quests:w2_sq05")),

        // World 3 Main Quests
        entry("campaign_w3_mq11", "w3_mq11", "MQ11: Homecoming", "World 3: The Spire", DebugScenarioCategory.STORY, "spire_sewers_landing",
            "Spire Sewers Landing beneath the lower city; full crew disembarked from Astra.",
            listOf("Engage and neutralize the hostile sewer crawler ambushes.",
                "Navigate the effluent maintenance conduits to Vent Output.",
                "Infiltrate the lower city through the service grates.",
                "Reach Zeke's safehouse apartment and establish the operational base."),
            listOf("Sewer crawler battles test party status recovery and team synergy.",
                "Vent output exit transitions legally to lower city streets.",
                "Safehouse arrival unlocks Lower City hub nodes and completes Homecoming."),
            setOf("quests:w3_mq11", "enemies:sewer_crawler")),

        entry("campaign_w3_mq12", "w3_mq12", "MQ12: The Plan", "World 3: The Spire", DebugScenarioCategory.STORY, "spire_zekes_apartment",
            "Zeke's Safehouse in Lower City; planning the infiltration into the Upper City Archive.",
            listOf("Speak with Jax at The Static bar to gather security patrol schedules.",
                "Interrogate a corrupt guard at the security kiosk and copy access badges.",
                "Source high-society Upper City disguises from the laundry service.",
                "Assemble the heist plan at Zeke's apartment table."),
            listOf("Multiple dialogue investigation paths update heist prep progress.",
                "Disguise and badge acquisition update quest task flags.",
                "Heist planning assembly completes The Plan and opens Upper City access."),
            setOf("quests:w3_mq12", "dialogue:w3_sq11_jax_intro")),

        entry("campaign_w3_mq13", "w3_mq13", "MQ13: Social Engineering", "World 3: The Spire", DebugScenarioCategory.STORY, "spire_laundry_service",
            "Upper City Laundry Service with disguises equipped; infiltrating the Skypark.",
            listOf("Pass the Skypark Dome guest registry using forged credentials.",
                "Disable the acoustic sensor grid in the service conduits.",
                "Blend in among the elite socialites in the Grand Concourse.",
                "Infiltrate the restricted Archive Vault security lobby."),
            listOf("Disguise check prevents security alarm triggers in the Skypark.",
                "Sensor grid puzzle disables perimeter turrets.",
                "Lobby infiltration completes Social Engineering."),
            setOf("quests:w3_mq13")),

        entry("campaign_w3_mq14", "w3_mq14", "MQ14: The Lens", "World 3: The Spire", DebugScenarioCategory.STORY, "spire_skypark_dome",
            "Archive Approach approaching the vault containment field; full crew ready.",
            listOf("Enter the Archive Vault from the Skypark approach.",
                "Inspect the containment field emitter and read the prism shutters.",
                "Solve the chromatic light alignment puzzle to drop the force field.",
                "Claim The Lens relic from the central pedestal."),
            listOf("Prism shutter puzzle verifies color reflection logic.",
                "Containment field drops cleanly upon puzzle solution.",
                "The Lens is added to inventory, unlocking Source Art Scan."),
            setOf("quests:w3_mq14", "items:the_lens", "skills:source_art_scan")),

        entry("campaign_w3_mq15", "w3_mq15", "MQ15: Burn Notice", "World 3: The Spire", DebugScenarioCategory.STORY, "spire_archive_vault",
            "Archive Vault with alarms blaring after taking The Lens; lockdown active.",
            listOf("Fight through elite Dominion security forces toward the landing roof.",
                "Engage and defeat the Spire Administrator boss encounter.",
                "Use The Lens to scan the planetary defense shield gap from the roof.",
                "Signal the Astra for hot extraction and launch toward the Foundry."),
            listOf("Alarm gauntlet spawns heavy mech and drone security waves.",
                "Administrator boss features heavy barriers and support summons.",
                "Shield gap scan enables Astra escape to World 4: The Foundry."),
            setOf("quests:w3_mq15", "enemies:administrator_boss")),

        // World 3 Side Quests
        entry("campaign_w3_sq11", "w3_sq11", "SQ11: Neon Fix", "World 3: The Spire", DebugScenarioCategory.CONTENT, "spire_the_static",
            "Outside The Static in Lower City; Jax needs help fixing the bar's neon sign.",
            listOf("Inspect the flickering neon sign power conduit outside The Static.",
                "Diagnose the blown surge resistor in the junction box.",
                "Install a spare power core to restore the circuit.",
                "Verify the neon sign lights up and speak with Jax."),
            listOf("Sign junction diagnosis checks electrical components.",
                "Installing power core updates room visual state.",
                "Jax awards drinks and credits upon completion."),
            setOf("quests:w3_sq11")),

        entry("campaign_w3_sq12", "w3_sq12", "SQ12: Cold Case", "World 3: The Spire", DebugScenarioCategory.CONTENT, "spire_security_kiosk",
            "Security Kiosk in Lower City with Gh0st; investigating an erased cold case.",
            listOf("Access the memorial terminal in Uniform Sorting to find the case number.",
                "Hack into the transit security kiosk database with Gh0st.",
                "Expose the unauthorized personnel transfer order.",
                "Confront the corrupt precinct officer with the evidence."),
            listOf("Memorial inspection uncovers the scrubbed incident ID.",
                "Database hack verifies Gh0st's decryption capabilities.",
                "Exposing the transfer completes the case and awards tactical mod."),
            setOf("quests:w3_sq12")),

        entry("campaign_w3_sq13", "w3_sq13", "SQ13: Night Market Run", "World 3: The Spire", DebugScenarioCategory.CONTENT, "spire_night_market",
            "Spire Night Market with Mika; investigating illicit power siphoning.",
            listOf("Trace the illegal power conduit under the market stalls.",
                "Confront the rogue scrapper siphoning energy from the lantern bridge.",
                "Reroute the power flow to stabilize the vendor grid.",
                "Report back to Mika at her food stall."),
            listOf("Power trace highlights hidden cabling through market alleys.",
                "Confrontation can be resolved through combat or dialogue.",
                "Market lighting restores and Mika awards signature street food."),
            setOf("quests:w3_sq13")),

        entry("campaign_w3_sq14", "w3_sq14", "SQ14: Corporate Espionage", "World 3: The Spire", DebugScenarioCategory.CONTENT, "spire_exec_lounge_bar",
            "Upper City Executive Lounge; searching for Dominion financial ledgers.",
            listOf("Copy the concierge key from the lounge mirror terminal.",
                "Infiltrate the executive private suite via the service lift.",
                "Steal the encrypted offshore transactions ledger from the safe.",
                "Transmit the leak to the underground resistance network."),
            listOf("Concierge credential copy bypasses executive elevator lock.",
                "Safe safe-cracking puzzle tests lockpicking proficiency.",
                "Leaking the ledger grants substantial credits and resistance rep."),
            setOf("quests:w3_sq14")),

        entry("campaign_w3_sq15", "w3_sq15", "SQ15: Prototype Testing", "World 3: The Spire", DebugScenarioCategory.CONTENT, "spire_drone_test_alcove",
            "Drone Test Alcove in Upper City; testing experimental prototype weaponry.",
            listOf("Scan the prototype targeting drone's firmware bias in the alcove.",
                "Engage live combat drone waves using the prototype weapon.",
                "Scrub telemetry data to conceal the unauthorized weapon test.",
                "Deliver test results to the hacked terminal contact."),
            listOf("Firmware scan exposes unique prototype targeting strengths.",
                "Combat waves validate the prototype's high-damage charge mode.",
                "Telemetry scrub completes the quest and retains the prototype mod."),
            setOf("quests:w3_sq15")),

        // World 4 Main Quests
        entry("campaign_w4_mq16", "w4_mq16", "MQ16: Into the Fire", "World 4: The Foundry", DebugScenarioCategory.STORY, "foundry_slag_landing",
            "Foundry Slag Landing on the Obsidian Shelf; Astra docked amidst molten rivers.",
            listOf("Secure the Astra's landing struts on the fragile obsidian crust.",
                "Navigate across the molten Slag River using moving crust stepping stones.",
                "Hack into the primary cooling vents to depressurize the sector.",
                "Breach the outer service airlock to access the Foundry interior."),
            listOf("Obsidian crust traversal tests hazardous terrain timing.",
                "Cooling vent hack lowers ambient sector heat levels.",
                "Airlock entry unlocks the Slag Pits hub and completes quest."),
            setOf("quests:w4_mq16")),

        entry("campaign_w4_mq17", "w4_mq17", "MQ17: Ghost in the Machine", "World 4: The Foundry", DebugScenarioCategory.STORY, "foundry_waste_intake",
            "Foundry Waste Intake terminal; uncovering records of Project Phantom.",
            listOf("Access the scrubbed Project Phantom terminal in Waste Intake.",
                "Recover Gh0st's erased unit records and override protocols.",
                "Fight through malfunctioning automated security mechs.",
                "Regroup with the crew at the geothermal cooling springs."),
            listOf("Phantom terminal decrypts Gh0st's backstory lore.",
                "Automated mech encounters test anti-armor strategies.",
                "Arrival at cooling springs completes the quest and heals party."),
            setOf("quests:w4_mq17")),

        entry("campaign_w4_mq18", "w4_mq18", "MQ18: The Assembly", "World 4: The Foundry", DebugScenarioCategory.STORY, "foundry_conditioning_chamber",
            "Foundry Conditioning Chamber overlooking the moving assembly conveyor lines.",
            listOf("Navigate the hazardous conveyor belts avoiding industrial crushers.",
                "Defeat prototype combat mechs rolling off the active production line.",
                "Access the main power matrix control panel.",
                "Overload the production matrix to halt automated war droid fabrication."),
            listOf("Conveyor traversal requires timing movement between crusher strokes.",
                "Production line mechs drop valuable alloy crafting components.",
                "Matrix overload permanently disables droid assembly in the sector."),
            setOf("quests:w4_mq18")),

        entry("campaign_w4_mq19", "w4_mq19", "MQ19: The Anvil", "World 4: The Foundry", DebugScenarioCategory.STORY, "foundry_belt_service_walk",
            "Belt Service Walk approaching the colossal Foundry Forge.",
            listOf("Infiltrate the core forge chamber through the intake flues.",
                "Solve the thermal radiator balance puzzle to cool the forge anvil.",
                "Open the anvil containment cradle.",
                "Claim The Anvil relic to unlock Source Art Construct."),
            listOf("Radiator puzzle requires balancing coolant between three furnace loops.",
                "Anvil cradle opening triggers forge environmental effects.",
                "The Anvil relic adds to inventory and unlocks Nova's construct power."),
            setOf("quests:w4_mq19", "items:the_anvil", "skills:source_art_construct")),

        entry("campaign_w4_mq20", "w4_mq20", "MQ20: Meltdown", "World 4: The Foundry", DebugScenarioCategory.STORY, "foundry_forge_anvil",
            "Foundry Forge Anvil with Commander Rylos blocking the exit with the Titan Walker.",
            listOf("Confront Commander Rylos at the Titan Walker dock.",
                "Engage and destroy the Titan Walker boss in multi-phase combat.",
                "Steal the deep core engine and phase cutter arrays from the loading gantry.",
                "Escape the melting facility aboard the Astra into orbital space."),
            listOf("Titan Walker encounter tests breaking heavy structural armor plates.",
                "Engine theft sequence triggers a timed evacuation countdown.",
                "Astra launch successfully transitions to World 5: The Void."),
            setOf("quests:w4_mq20", "enemies:titan_walker_boss")),

        // World 4 Side Quests
        entry("campaign_w4_sq16", "w4_sq16", "SQ16: Sabotage", "World 4: The Foundry", DebugScenarioCategory.CONTENT, "foundry_slag_river",
            "Slag River in the Foundry; resistance contact ordered destruction of munitions.",
            listOf("Locate marked ammunition crate Alpha at the Slag River crossing.",
                "Plant thermite charges on ammunition crate Beta near Waste Intake.",
                "Detonate ammunition crate Gamma inside the munitions storage alcove.",
                "Evacuate the blast zone to complete the sabotage mission."),
            listOf("Each crate requires planting explosive charges and surviving security retaliation.",
                "Munitions detonations update room destruction states.",
                "Resistance awards heavy ordinance and weapon mods."),
            setOf("quests:w4_sq16")),

        entry("campaign_w4_sq17", "w4_sq17", "SQ17: Lost Worker", "World 4: The Foundry", DebugScenarioCategory.CONTENT, "foundry_cooling_springs",
            "Cooling Springs in the Foundry; tracking a maintenance engineer trapped by molten slag.",
            listOf("Trace the worker's emergency locator ping from Cooling Springs.",
                "Navigate the rising slag flow to locate the trapped worker in the vent alcove.",
                "Vent the high-pressure steam line to create a safe escape corridor.",
                "Escort the engineer to the safety of the service airlock."),
            listOf("Ping tracker guides navigation through heat-damaged rooms.",
                "Steam venting mechanic clears the burning blockage.",
                "Rescued worker awards rare heat-resistant alloy schematics."),
            setOf("quests:w4_sq17")),

        entry("campaign_w4_sq18", "w4_sq18", "SQ18: The Scrap Heap", "World 4: The Foundry", DebugScenarioCategory.CONTENT, "foundry_waste_intake",
            "Waste Intake in the Foundry; scrapper drone spotted valuable mech carcasses.",
            listOf("Engage the intake emergency brake before machinery crushes the wrecks.",
                "Salvage intact military servos and processors from the crushed mechs.",
                "Construct an automated salvage bypass circuit.",
                "Secure the scrap cache for future Astra upgrades."),
            listOf("Emergency brake puzzle tests quick interaction under pressure.",
                "Mech salvage awards high-tier crafting components.",
                "Bypass circuit ensures ongoing resource acquisition."),
            setOf("quests:w4_sq18")),

        entry("campaign_w4_sq19", "w4_sq19", "SQ19: Quality Control", "World 4: The Foundry", DebugScenarioCategory.CONTENT, "foundry_reject_bay",
            "Reject Bay in Assembly Line; inspecting sentient droids flagged for destruction.",
            listOf("Inspect the rejected droid unit and read the rejection diagnostic code.",
                "Discover the droid rejected Dominion war protocols due to emerging sentience.",
                "Reprogram the reject bay incinerator routing to create an escape path.",
                "Release the surviving units into the lower waste tunnels."),
            listOf("Diagnostic reading reveals narrative themes of artificial consciousness.",
                "Reprogramming puzzle bypasses the automatic purge lasers.",
                "Droid release grants ally assistance and unique defensive mod."),
            setOf("quests:w4_sq19")),

        entry("campaign_w4_sq20", "w4_sq20", "SQ20: Overclocked", "World 4: The Foundry", DebugScenarioCategory.CONTENT, "foundry_forge_control_alcove",
            "Control Alcove in the Forge; testing hazardous overclocking limits.",
            listOf("Inspect the forge hazard cycle telemetry map at the control terminal.",
                "Survive intense enemy defense waves during the automated stress test.",
                "Manage temperature spikes using the emergency coolant valves.",
                "Extract the stabilized Overclock Module from the terminal."),
            listOf("Wave combat tests party endurance against relentless fire elements.",
                "Coolant valve management prevents fatal party overheat debuffs.",
                "Reward is the powerful Overclock relic modification."),
            setOf("quests:w4_sq20")),

        // World 5 Main Quests
        entry("campaign_w5_mq21", "w5_mq21", "MQ21: Docking Procedure", "World 5: The Void", DebugScenarioCategory.STORY, "orbital_executive_dock",
            "Orbital Ring Executive Dock; Astra breaching the Dominion orbital stronghold.",
            listOf("Approach the Orbital Ring defensive halo amidst void fighter fire.",
                "Target and neutralize orbital interceptor defensive screens.",
                "Force an emergency docking clamp onto the Executive Airlock.",
                "Hack the pressurized airlock controls to board the station interior."),
            listOf("Docking sequence features zero-gravity ship combat mechanics.",
                "Airlock hack tests high-level electronic decryption.",
                "Station entry establishes World 5 foothold and completes quest."),
            setOf("quests:w5_mq21", "enemies:orbital_fighter")),

        entry("campaign_w5_mq22", "w5_mq22", "MQ22: Zero G", "World 5: The Void", DebugScenarioCategory.STORY, "orbital_solarium",
            "Orbital Solarium with artificial beach and sun simulator; traversing the ring.",
            listOf("Traverse the synthetic biosphere Solarium under low gravity.",
                "Engage and neutralize Dominion Compliance security forces.",
                "Descend the zero-gravity elevator service shaft into the Deep Ring.",
                "Locate defecting Dominion scientist Thorne in the Mainframe Nave."),
            listOf("Zero-G traversal modifies party agility and movement properties.",
                "Compliance officers utilize disorienting stun and suppressive arts.",
                "Thorne dialogue reveals the location of Elara and The Anchor."),
            setOf("quests:w5_mq22", "enemies:compliance_officer")),

        entry("campaign_w5_mq23", "w5_mq23", "MQ23: The Core Approach", "World 5: The Void", DebugScenarioCategory.STORY, "deep_firewall_alpha",
            "Deep Server Farm entering the core approach; firewall constructs active.",
            listOf("Navigate the labyrinthine server farm corridors.",
                "Bypass Firewall Alpha using the coolant pulse alignment.",
                "Deactivate Firewall Beta by severing the secondary power bus.",
                "Destroy the Firewall Gamma construct guarding the central vault."),
            listOf("Server maze features shifting security walls and patrol drones.",
                "Firewall deactivation requires coordinating puzzle switches across rooms.",
                "Construct boss fight tests piercing heavy digital barrier shields."),
            setOf("quests:w5_mq23", "enemies:firewall_construct")),

        entry("campaign_w5_mq24", "w5_mq24", "MQ24: The Anchor", "World 5: The Void", DebugScenarioCategory.STORY, "deep_firewall_gamma",
            "Threshold of the Anchor Chamber; sensing Elara's psychic resonance.",
            listOf("Enter the fortified Anchor Chamber.",
                "Locate Elara held in stasis at the center of the resonance spire.",
                "Commune with Elara to unbind the station's anchor matrix.",
                "Claim The Anchor relic, unlocking Source Art Stasis."),
            listOf("Chamber entry triggers emotional cinematic dialogue with Elara.",
                "Unbinding sequence releases station structural tension.",
                "The Anchor relic enters inventory, granting group stasis power."),
            setOf("quests:w5_mq24", "items:anchor_relic", "skills:source_art_stasis")),

        entry("campaign_w5_mq25", "w5_mq25", "MQ25: Critical Mass", "World 5: The Void", DebugScenarioCategory.STORY, "deep_anchor_chamber",
            "Station destabilizing into critical mass; advancing to Vale's Throne Room.",
            listOf("Navigate collapsing station sectors toward the apex throne room.",
                "Confront Director Vale and witness the Soloist ascension ritual.",
                "Defeat the Compliance Avatar guarding the Tear breach.",
                "Leap through the dimensional Tear into the Source."),
            listOf("Timed traversal through decompression hazards and falling debris.",
                "Avatar boss fight features phase shifting and void vortexes.",
                "Tear traversal completes World 5 and enters World 6: The Source."),
            setOf("quests:w5_mq25", "enemies:compliance_avatar")),

        // World 5 Side Quests
        entry("campaign_w5_sq21", "w5_sq21", "SQ21: Employee of the Month", "World 5: The Void", DebugScenarioCategory.CONTENT, "orbital_security_hub",
            "Security Hub in the Orbital Ring; investigating Director redaction logs.",
            listOf("Access the high-clearance security terminal in the Security Hub.",
                "Find and reconstruct heavily redacted execution order logs.",
                "Expose the truth behind the colony sacrifice quotas.",
                "Broadcast the unredacted logs across all Dominion network nodes."),
            listOf("Terminal decryption minigame reconstructs missing text lines.",
                "Unredacted logs provide critical narrative reveals on colony origins.",
                "Broadcast awards massive XP and unique investigator title mod."),
            setOf("quests:w5_sq21")),

        entry("campaign_w5_sq22", "w5_sq22", "SQ22: Solar Maintenance", "World 5: The Void", DebugScenarioCategory.CONTENT, "orbital_mirror_walk",
            "Orbital Mirror Walk; realigning solar focusing mirrors.",
            listOf("Walk the exterior mirror array overlooking the planet below.",
                "Inspect the faulty mirror tracking actuators along the path.",
                "Realign mirror banks Alpha, Beta, and Gamma to the true sun vector.",
                "Restore natural light to the Solarium hydroponic gardens."),
            listOf("Exterior space walk features stunning orbital panoramic presentation.",
                "Actuator alignment requires calculating optimal solar angles.",
                "Garden restoration rewards rare exotic cooking and alchemy herbs."),
            setOf("quests:w5_sq22")),

        entry("campaign_w5_sq23", "w5_sq23", "SQ23: Vacuum Seal", "World 5: The Void", DebugScenarioCategory.CONTENT, "orbital_executive_dock",
            "Executive Dock; repairing hull breaches leaking station atmosphere.",
            listOf("Inspect the station atmospheric pressure telemetry map.",
                "Locate three micro-meteorite hull breaches in the outer ring.",
                "Apply composite patch plates using the thermal welder.",
                "Re-pressurize the sector to restore environmental stability."),
            listOf("Pressure map monitors oxygen countdown during repair tasks.",
                "Thermal welding interactions consume patch materials from inventory.",
                "Sealing all breaches restores safety and opens vendor access."),
            setOf("quests:w5_sq23")),

        entry("campaign_w5_sq24", "w5_sq24", "SQ24: Ghost in the Shell", "World 5: The Void", DebugScenarioCategory.CONTENT, "orbital_server_farm",
            "Orbital Server Farm; recovering Gh0st's purged prototype backup.",
            listOf("Trace the purge command origin across the server farm racks.",
                "Recover the fragmented personality backup core from rack 07.",
                "Reconstruct the corrupted neural clusters at the diagnostic desk.",
                "Integrate the backup into Gh0st's combat subroutines."),
            listOf("Server rack search requires parsing system error logs.",
                "Neural reconstruction puzzle aligns memory clusters.",
                "Integration upgrades Gh0st's critical strike and evasion stats."),
            setOf("quests:w5_sq24")),

        entry("campaign_w5_sq25", "w5_sq25", "SQ25: Admin Privileges", "World 5: The Void", DebugScenarioCategory.CONTENT, "deep_sysadmin_nest",
            "SysAdmin Nest in the Deep Ring; searching for master clearance keycards.",
            listOf("Locate the deceased Chief SysAdmin in the secluded nest alcove.",
                "Recover the biometric clearance keycard from the terminal desk.",
                "Unlock the sealed high-security armory in the Throne Room corridor.",
                "Claim the classified Dominion military prototype weapons."),
            listOf("Hidden alcove search encourages thorough exploration of side passages.",
                "Master keycard opens locked armory doors across the entire station.",
                "Armory contains endgame armor and weapon upgrades."),
            setOf("quests:w5_sq25")),

        // World 6 Main Quests
        entry("campaign_w6_mq26", "w6_mq26", "MQ26: Fractured Minds", "World 6: The Source", DebugScenarioCategory.STORY, "source_campfire",
            "Source Campfire beyond the Tear; crew separated in psychic nightmare domains.",
            listOf("Enter Zeke's nightmare review loop and remind him of his true identity.",
                "Enter Gh0st's kill suite simulation and shatter the endless combat loop.",
                "Enter Orion's silent tide well and restore his voice with the Chime.",
                "Reassemble the reunited crew at the Source Campfire."),
            listOf("Each nightmare world features unique surreal visuals and dialogue.",
                "Psychic rescue combats require exploiting individual crew weaknesses.",
                "Reassembling the crew restores full four-character party capabilities."),
            setOf("quests:w6_mq26")),

        entry("campaign_w6_mq27", "w6_mq27", "MQ27: Echo of the Mines", "World 6: The Source", DebugScenarioCategory.STORY, "source_campfire",
            "Source Campfire preparing to step into the distorted memory of the Homestead mines.",
            listOf("Step into the distorted memory representation of World 1.",
                "Evade the shadowy Manager Projection patrolling the twisted tunnels.",
                "Locate the reconstructed Deep Elevator at the heart of the illusion.",
                "Claim the Key Relic to unlock the path toward the center."),
            listOf("Distorted mine rooms feature surreal inverted gravity and shifting walls.",
                "Manager projection encounter tests stealth and evasive maneuvers.",
                "Key Relic acquisition unlocks the Memory Bridge across the void."),
            setOf("quests:w6_mq27", "items:key_relic")),

        entry("campaign_w6_mq28", "w6_mq28", "MQ28: The Crossing", "World 6: The Source", DebugScenarioCategory.STORY, "source_echo_mines",
            "Approaching the Memory Bridge span over the abyss of unwritten space.",
            listOf("Set Zeke's anchor on the western bridge pedestal.",
                "Set Gh0st's anchor and Orion's anchor to solidify the light span.",
                "Cross the completed bridge span with the full crew sharing final banter.",
                "Reach the Singularity Threshold at the base of the Spire of Thought."),
            listOf("Pedestal anchor sequence visualizes the bond between all four heroes.",
                "Bridge crossing features poignant character reflections on their journey.",
                "Reaching the threshold completes the crossing and unlocks Hub 12."),
            setOf("quests:w6_mq28")),

        entry("campaign_w6_mq29", "w6_mq29", "MQ29: The Spire of Thought", "World 6: The Source", DebugScenarioCategory.STORY, "source_memory_stair",
            "Memory Stair ascending toward the Center of the Source; Vale reshaping reality.",
            listOf("Ascend the shifting steps of the Memory Stair.",
                "Refuse Jed's revision illusion offering comfortable surrender in the mines.",
                "Refuse the Astra and Foundry revision temptations.",
                "Defeat the nightmare shadow wave blocking the entrance to the Center."),
            listOf("Revision temptations test player narrative resolve against illusions.",
                "Shadow wave combat features distorted versions of past bosses.",
                "Breaching the summit opens the final confrontation chamber."),
            setOf("quests:w6_mq29")),

        entry("campaign_w6_mq30", "w6_mq30", "MQ30: The Final Note", "World 6: The Source", DebugScenarioCategory.STORY, "source_center",
            "Center of the Source; confronting Ascended Vale at the heart of reality.",
            listOf("Confront Ascended Director Vale at the tuning center.",
                "Defeat Ascended Vale in high-intensity multi-form combat.",
                "Defeat the Ascended God manifestation using all four Source Arts.",
                "Execute Source Art: Tune World to complete the campaign and unlock NG+."),
            listOf("Grand finale combat tests full mastery of combat mechanics, buffs, and arts.",
                "World tuning sequence rolls the authored ending cinematic and credits.",
                "Completing quest awards ms_game_complete and enables New Game Plus."),
            setOf("quests:w6_mq30", "enemies:ascended_vale", "milestones:ms_game_complete")),

        // World 6 Side Quests
        entry("campaign_w6_sq26", "w6_sq26", "SQ26: Jed's Echo", "World 6: The Source", DebugScenarioCategory.CONTENT, "source_echo_workbench",
            "Answering Chorus in the Source; discovering an echo of Jed's workbench.",
            listOf("Examine the crooked tool marks on the spectral workbench.",
                "Speak with the echo of Jed about the meaning of survival and sacrifice.",
                "Craft the final Masterwork Induction Coil using Source light.",
                "Carry Jed's legacy forward into the new world."),
            listOf("Emotional narrative interaction concluding Jed's mentorship arc.",
                "Crafting interaction validates recipe knowledge without requiring materials.",
                "Awards the unique Mentor's Keepsake accessory."),
            setOf("quests:w6_sq26")),

        entry("campaign_w6_sq27", "w6_sq27", "SQ27: The HR Record", "World 6: The Source", DebugScenarioCategory.CONTENT, "source_zeke_review_loop",
            "Infinite Cubicle in the Source; confronting the bureaucratic nightmare lattice.",
            listOf("Locate the endless backup lattice continually recreating Zeke's file.",
                "Revoke the mandatory retirement flag from the Dominion root register.",
                "Permanently delete the personnel file from existence.",
                "Leave a scathing final employee performance review."),
            listOf("Surreal satire of corporate bureaucracy in a cosmic horror setting.",
                "Terminal interactions allow comical choices with unique response texts.",
                "Zeke gains permanent confidence and morale stat buffs."),
            setOf("quests:w6_sq27")),

        entry("campaign_w6_sq28", "w6_sq28", "SQ28: Elara's Song", "World 6: The Source", DebugScenarioCategory.CONTENT, "source_gh0st_kill_suite",
            "Endless War domain in the Source; recovering Elara's buried song.",
            listOf("Isolate Elara's voice beneath the deafening military command signals.",
                "Break the command suppression layer with harmonic pulse tuning.",
                "Recover the complete recorded audio song of the Source.",
                "Play the melody to pacify hostile lingering memory phantoms."),
            listOf("Audio frequency puzzle requires matching musical tone intervals.",
                "Suppression break clears hostile distortion effects from the sector.",
                "Reward is the calming Melody of the Ancients buff item."),
            setOf("quests:w6_sq28")),

        entry("campaign_w6_sq29", "w6_sq29", "SQ29: The Aethel Grave", "World 6: The Source", DebugScenarioCategory.CONTENT, "source_memory_fragments",
            "Singularity Threshold; discovering the resting place of the ancient builders.",
            listOf("Trace the ancient names inscribed beneath the cosmic light pillars.",
                "Locate the communal memorial grave of the vanished Aethel civilization.",
                "Tune the memorial resonance crystal to honor their memory.",
                "Absorb their chorus into Orion's ancestral prism."),
            listOf("Deep worldbuilding revelations detailing ancient history.",
                "Crystal tuning puzzle aligns ancient geometric harmonies.",
                "Orion unlocks the Ancestral Grace ultimate recovery art."),
            setOf("quests:w6_sq29")),

        entry("campaign_w6_sq30", "w6_sq30", "SQ30: The Final Scavenge", "World 6: The Source", DebugScenarioCategory.CONTENT, "source_spire_archive",
            "Spire of Thought Archive; inspecting the wreckage of future timelines.",
            listOf("Inspect the timeline wreckage archives for impossible starship components.",
                "Recover the futuristic hull plate from an unwritten timeline.",
                "Fit the hull plating to the Astra's spectral frame.",
                "Prepare the ship to carry the crew into any reality."),
            listOf("Fascinating temporal anomaly artifacts to examine.",
                "Hull fitting interaction permanently upgrades ship defenses.",
                "Quest completes the 100% side quest completion milestone."),
            setOf("quests:w6_sq30"))
    )

    val startRooms: Map<String, String> = mapOf(
        "w1_mq02" to "workshop_yard",
        "w1_mq03" to "admin_lobby",
        "w1_mq04" to "echo_gap",
        "w1_mq05" to "launch_lift",
        "w1_sq01" to "trade_strip",
        "w1_sq02" to "medbay_exam1",
        "w1_sq03" to "admin_lobby",
        "w1_sq04" to "server_hub",
        "w1_sq05" to "mine_junction",
        "w2_mq01" to "sector9_crash_site",
        "w2_mq02" to "sector9_landing_stream",
        "w2_mq03" to "sector9_hall_of_echoes",
        "w2_mq04" to "sector9_canopy_ridge",
        "w2_mq05" to "sector9_source_gate",
        "w2_sq01" to "sector9_canopy",
        "w2_sq02" to "sector9_wilds_thickets",
        "w2_sq03" to "sector9_beach_pools",
        "w2_sq04" to "sector9_hall_of_echoes",
        "w2_sq05" to "sector9_vents_gantry",
        "w3_mq11" to "spire_sewers_landing",
        "w3_mq12" to "spire_zekes_apartment",
        "w3_mq13" to "spire_laundry_service",
        "w3_mq14" to "spire_skypark_dome",
        "w3_mq15" to "spire_archive_vault",
        "w3_sq11" to "spire_the_static",
        "w3_sq12" to "spire_security_kiosk",
        "w3_sq13" to "spire_night_market",
        "w3_sq14" to "spire_exec_lounge_bar",
        "w3_sq15" to "spire_drone_test_alcove",
        "w4_mq16" to "foundry_slag_landing",
        "w4_mq17" to "foundry_waste_intake",
        "w4_mq18" to "foundry_conditioning_chamber",
        "w4_mq19" to "foundry_belt_service_walk",
        "w4_mq20" to "foundry_forge_anvil",
        "w4_sq16" to "foundry_slag_river",
        "w4_sq17" to "foundry_cooling_springs",
        "w4_sq18" to "foundry_waste_intake",
        "w4_sq19" to "foundry_reject_bay",
        "w4_sq20" to "foundry_forge_control_alcove",
        "w5_mq21" to "orbital_executive_dock",
        "w5_mq22" to "orbital_solarium",
        "w5_mq23" to "deep_firewall_alpha",
        "w5_mq24" to "deep_firewall_gamma",
        "w5_mq25" to "deep_anchor_chamber",
        "w5_sq21" to "orbital_security_hub",
        "w5_sq22" to "orbital_mirror_walk",
        "w5_sq23" to "orbital_executive_dock",
        "w5_sq24" to "orbital_server_farm",
        "w5_sq25" to "deep_sysadmin_nest",
        "w6_mq26" to "source_campfire",
        "w6_mq27" to "source_campfire",
        "w6_mq28" to "source_echo_mines",
        "w6_mq29" to "source_memory_stair",
        "w6_mq30" to "source_center",
        "w6_sq26" to "source_echo_workbench",
        "w6_sq27" to "source_zeke_review_loop",
        "w6_sq28" to "source_gh0st_kill_suite",
        "w6_sq29" to "source_memory_fragments",
        "w6_sq30" to "source_spire_archive"
    )

    private fun entry(
        id: String,
        questId: String,
        title: String,
        world: String,
        category: DebugScenarioCategory,
        roomId: String,
        startingState: String,
        steps: List<String>,
        expected: List<String>,
        coverageIds: Set<String>
    ): DebugScenario {
        val procedure = DebugTestProcedure(
            fixture = DebugFixture.CAMPAIGN_CHECKPOINT,
            startingState = startingState,
            steps = steps,
            expected = expected,
            coverageIds = coverageIds,
            limitations = "Campaign checkpoint starting before the target quest action. Synthetic baseline matches authored progression.",
            targetId = questId
        )
        return DebugScenario(
            id = id,
            title = title,
            description = startingState,
            category = category,
            destination = DebugScenarioDestination.EXPLORATION,
            worldLabel = world,
            procedure = procedure
        )
    }
}
