const $=s=>document.querySelector(s),base='../app/src/main/assets/';
const files={worlds:'worlds',hubs:'hubs',rooms:'rooms',quests:'quests',enemies:'enemies',items:'items',skills:'skills',characters:'characters',statuses:'statuses',cinematics:'cinematics',audio:'audio_catalog'};let D={},section='story',query='';
const list=k=>Array.isArray(D[k])?D[k]:[],label=x=>x?.title||x?.name||x?.id||'Untitled',matches=x=>JSON.stringify(x).toLowerCase().includes(query);
async function boot(){for(const [k,f] of Object.entries(files)){try{D[k]=await fetch(base+f+'.json').then(r=>r.json())}catch(e){D[k]=[]}}$('#status').textContent='INDEX READY';$('#updated').textContent=Object.values(D).reduce((n,x)=>n+(Array.isArray(x)?x.length:0),0)+' records loaded';render()}
function box(title,body){return '<div class="card"><h2>'+title+'</h2>'+body+'</div>'}function metric(n,t){return '<div class="metric"><label>'+t+'</label><strong>'+n+'</strong></div>'}function render(){document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));$('#title').textContent={story:'Story Navigator',quests:'Quests & State Explorer',entities:'Entity Library',audio:'Audio Lab',audits:'Audit Center'}[section];({story,quests,entities,audio,audits}[section])()}
function story(){let ws=list('worlds');$('#app').innerHTML='<div class="metrics">'+metric(ws.length,'WORLDS')+metric(list('quests').length,'QUESTS')+metric(list('cinematics').length,'CINEMATICS')+metric(list('rooms').length,'ROOMS')+'</div>'+box('Campaign spine','<p class="lead">Follow the authored campaign from world to hub to room. Each layer is backed by the game assets and remains read-only.</p><div class="world-list">'+ws.map((w,i)=>'<div class="world"><div class="world-row"><b>'+String(i+1).padStart(2,'0')+' / '+label(w)+'</b><em>'+(w.default_theme||'THEME')+'</em></div><p>'+(w.description||'')+'</p></div>').join('')+'</div>')}
function quests(){let xs=list('quests').filter(matches);$('#app').innerHTML='<div class="toolbar"><input id="query" placeholder="Search quests, stages, triggers..." value="'+query+'"></div>'+box('Quest records','<table><thead><tr><th>QUEST</th><th>AUTHORED FIELDS</th></tr></thead><tbody>'+xs.map(x=>'<tr><td><b>'+label(x)+'</b><br><span class="label">'+(x.id||'')+'</span></td><td>'+Object.keys(x).join(', ')+'</td></tr>').join('')+'</tbody></table>')}
function entities(){let groups={Enemies:'enemies',Abilities:'skills',Items:'items',Characters:'characters',Statuses:'statuses'},out='<div class="toolbar"><input id="query" placeholder="Search entities..." value="'+query+'"></div>';for(let [t,k] of Object.entries(groups)){let xs=list(k).filter(matches);out+=box(t,'<div class="entity-grid">'+xs.map(x=>'<div class="entity"><b>'+label(x)+'</b><span>'+(x.id||'')+'</span><small>'+(x.tier||x.type||x.combat_role||'')+'</small></div>').join('')+'</div>')}$('#app').innerHTML=out}
function audio(){let xs=list('audio');$('#app').innerHTML=box('Audio catalog',xs.map(x=>{let cue=x.id||x.name||'';return '<div class="audio-row"><div><b>'+label(x)+'</b><span>'+cue+'</span></div><audio controls preload="none" src="../app/src/main/res/raw/'+cue+'.mp3"></audio></div>'}).join(''))}function audits(){let missing=[];list('rooms').forEach(r=>Object.values(r.connections||{}).forEach(t=>{if(!list('rooms').some(x=>x.id===t))missing.push(r.id+' -> '+t)}));$('#app').innerHTML=box('Integrity findings',missing.length?missing.map(x=>'<div class="finding warning">! Missing room reference: '+x+'</div>').join(''):'<div class="finding good">No basic room reference errors found.</div>')}
function quests(){let xs=list('quests').filter(matches);let rows=xs.map((x,i)=>'<tr data-quest="'+i+'"><td><b>'+label(x)+'</b><br><span class="label">'+(x.id||'')+'</span></td><td>'+(x.giver||'—')+'</td><td>'+(x.stages?.length||0)+' stages</td><td>'+(x.rewards?.length||0)+' rewards</td></tr>').join('');$('#app').innerHTML='<div class="toolbar"><input id="query" placeholder="Search quests, stages, triggers..." value="'+query+'"></div>'+box('Quest lifecycle','<table><thead><tr><th>QUEST</th><th>GIVER</th><th>STAGES</th><th>REWARDS</th></tr></thead><tbody>'+rows+'</tbody></table>');document.querySelectorAll('[data-quest]').forEach(e=>e.onclick=()=>questDetail(xs[+e.dataset.quest]))}
function questDetail(x){let stages=(x.stages||[]).map((s,i)=>'<div class="world"><div class="world-row"><b>'+String(i+1).padStart(2,'0')+' / '+(s.title||s.id)+'</b><em>'+((s.tasks||[]).length)+' TASKS</em></div><p>'+ (s.description||'')+'</p><ol>'+((s.tasks||[]).map(t=>'<li>'+ (t.text||t.title||t.id)+'</li>').join(''))+'</ol></div>').join('');$('#app').innerHTML='<div class="toolbar"><button id="back">← Back to quests</button></div>'+box(x.title||x.id,'<span class="label">QUEST · '+x.id+' · GIVER: '+(x.giver||'UNKNOWN')+'</span><p class="lead">'+(x.description||x.summary||'')+'</p><h2>Stages and tasks</h2>'+stages+'<h2>Rewards</h2><pre>'+JSON.stringify(x.rewards||[],null,2)+'</pre>');$('#back').onclick=render}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;query='';render()});document.addEventListener('input',e=>{if(e.target.id==='query'){query=e.target.value;render()}});boot();
